FROM api_1th:Dockerfile

# Set the working directory
WORKDIR /app

# Install the Python packages from the requirements file
RUN python3 -m venv venv && \
    . venv/bin/activate && \
    pip3 install --upgrade pip && \
    pip3 install Flask flask_cors flask_swagger_ui opencv-python opencv-python-headless wheel dlib face_recognition setuptools
