#sudo docker build  -t "face_recognition_api_1th:v0.1" .

#sudo docker build --platform linux/amd64 -t face_recognition_api_1th:v0.1_mult .


#sudo docker buildx build --platform=linux/arm64,linux/amd64/v2 -t angelocarlotto/face_recognition_api_1th:latest_mult . --load 
# Use the official Ubuntu base image
#FROM ubuntu:latest
FROM ubuntu


# Update the package list and install dependencies
RUN apt-get update && apt-get install -y -q --allow-unauthenticated \
    build-essential \
    cmake \
    git \
    git-all\
    wget \
    curl \
    unzip \
    libopenblas-dev \
    liblapack-dev \
    libx11-dev \
    libgtk-3-dev \
    libboost-python-dev \
    python3 \
    python3-pip \
    python3-dev \
    python3.12-venv\
    && curl -fsSL -o install.sh https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN chmod 777 install.sh


RUN useradd -m -s /bin/zsh linuxbrew && \
    usermod -aG sudo linuxbrew &&  \
    mkdir -p /home/linuxbrew/.linuxbrew && \
    chown -R linuxbrew: /home/linuxbrew/.linuxbrew

USER linuxbrew
RUN NONINTERACTIVE=1 ./install.sh

USER root
RUN chown -R $CONTAINER_USER: /home/linuxbrew/.linuxbrew
ENV PATH="/home/linuxbrew/.linuxbrew/bin:${PATH}"
RUN git config --global --add safe.directory /home/linuxbrew/.linuxbrew/Homebrew
USER linuxbrew
RUN brew update
RUN brew doctor
RUN brew install gcc cmake

RUN apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /tmp/* \
    && rm -rf /var/tmp/*